dashboard.listeners.http.bind = 0.0.0.0:18083
dashboard.default_username = "admin"
dashboard.default_password = "public123"

listeners.tcp.default.bind = 0.0.0.0:1883
listeners.tcp.default.max_connections = 500

retainer.enable = false
delayed.enable = false

log.file.enable = true
log.file.level = warning
log.file.path = "/opt/emqx/log/emqx.log"

mqtt.max_packet_size = 1MB
mqtt.max_clientid_len = 128
